2014-11-05 13:39:01,061 - [INFO] - from play in pool-4-thread-2 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-11-05 13:39:05,390 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:39:05,943 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:40:20,862 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:40:20,917 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:40:20,930 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:40:20,955 - [DEBUG] - from application in play-akka.actor.default-dispatcher-4 
Clearing invalid session credentials

2014-11-05 13:40:42,715 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
Clearing invalid session credentials

2014-11-05 13:41:43,849 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:41:43,894 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:41:43,909 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:43:18,684 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:43:18,720 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:43:18,732 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:43:35,907 - [DEBUG] - from application in play-akka.actor.default-dispatcher-16 
User mfa access enabled but is nit authenticated

2014-11-05 13:43:35,908 - [DEBUG] - from application in play-akka.actor.default-dispatcher-16 
Clearing invalid session credentials

2014-11-05 13:48:06,260 - [ERROR] - from application in New I/O worker #7 


! @6k538c858 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: type User]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:297) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:292) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:292) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:325) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:325) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:325) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:107) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:105) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-11-05 13:49:51,011 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:49:51,049 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:49:51,060 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:49:51,113 - [ERROR] - from play in play-akka.actor.default-dispatcher-27 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-11-05 13:49:51,131 - [ERROR] - from application in play-akka.actor.default-dispatcher-27 


! @6k538i792 - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$overflowingExecutionContext$.execute(Execution.scala:73) [play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.link(Promise.scala:304) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.linkRootOf(Promise.scala:289) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$overflowingExecutionContext$.execute(Execution.scala:73) [play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.10-2.3.3.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.10-2.3.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: null
	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:49) ~[scala-library.jar:na]
	at scala.collection.immutable.StringOps.length(StringOps.scala:49) ~[scala-library.jar:na]
	at scala.collection.SeqLike$class.size(SeqLike.scala:106) ~[scala-library.jar:na]
	at scala.collection.immutable.StringOps.size(StringOps.scala:31) ~[scala-library.jar:na]
	at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69) ~[scala-library.jar:na]
	at scala.collection.immutable.VectorBuilder.sizeHint(Vector.scala:692) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:240) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:243) ~[scala-library.jar:na]
	at scala.collection.immutable.StringOps.map(StringOps.scala:31) ~[scala-library.jar:na]
	at views.html.main$.apply(main.template.scala:66) ~[classes/:na]
	at views.html.index$.apply(index.template.scala:37) ~[classes/:na]
	at views.html.index$.render(index.template.scala:56) ~[classes/:na]
	at views.html.index.render(index.template.scala) ~[classes/:na]
	at controllers.Application.index(Application.java:55) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:185) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:185) ~[classes/:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[scala-library.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[scala-library.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[play-iteratees_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	... 6 common frames omitted

2014-11-05 13:50:14,879 - [ERROR] - from application in New I/O worker #7 


! @6k538jgce - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[value getOptional is not a member of play.mvc.Http.Flash]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:297) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:292) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:292) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:325) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:325) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:325) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:107) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:105) ~[play_2.10-2.3.0-RC2.jar:2.3.0-RC2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2014-11-05 13:50:38,382 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:50:38,419 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:50:38,432 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:50:38,827 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:50:38,857 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:50:38,866 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:50:57,740 - [DEBUG] - from application in play-akka.actor.default-dispatcher-34 
User mfa access enabled but is not authenticated

2014-11-05 13:50:57,741 - [DEBUG] - from application in play-akka.actor.default-dispatcher-34 
Clearing invalid session credentials

2014-11-05 13:52:10,976 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
User mfa access enabled but is not authenticated

2014-11-05 13:52:10,976 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
Clearing invalid session credentials

2014-11-05 13:55:16,935 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:55:16,974 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:55:16,985 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:55:24,807 - [DEBUG] - from application in play-akka.actor.default-dispatcher-36 
User mfa access enabled but is not authenticated

2014-11-05 13:55:24,809 - [DEBUG] - from application in play-akka.actor.default-dispatcher-36 
Clearing invalid session credentials

2014-11-05 13:57:08,363 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 13:57:08,398 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 13:57:08,413 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 13:57:17,663 - [DEBUG] - from application in play-akka.actor.default-dispatcher-49 
MFA Callback - Access Token was null or empty

2014-11-05 13:57:17,690 - [DEBUG] - from application in play-akka.actor.default-dispatcher-50 
User mfa access enabled but is not authenticated

2014-11-05 13:57:17,690 - [DEBUG] - from application in play-akka.actor.default-dispatcher-50 
Clearing invalid session credentials

2014-11-05 14:01:23,162 - [DEBUG] - from application in play-akka.actor.default-dispatcher-55 
MFA Callback - Access Token was null or empty

2014-11-05 14:01:23,178 - [DEBUG] - from application in play-akka.actor.default-dispatcher-43 
User mfa access enabled but is not authenticated

2014-11-05 14:01:23,178 - [DEBUG] - from application in play-akka.actor.default-dispatcher-43 
Clearing invalid session credentials

2014-11-05 14:03:11,219 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:03:11,254 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:03:11,264 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:03:19,686 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
MFA Callback - Access Token was null or empty

2014-11-05 14:03:19,711 - [DEBUG] - from application in play-akka.actor.default-dispatcher-63 
User mfa access enabled but is not authenticated

2014-11-05 14:03:19,711 - [DEBUG] - from application in play-akka.actor.default-dispatcher-63 
Clearing invalid session credentials

2014-11-05 14:04:29,572 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:04:29,603 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:04:29,616 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:05:28,008 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:05:28,042 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:05:28,053 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:05:28,343 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:05:28,372 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:05:28,381 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:05:39,634 - [DEBUG] - from application in play-akka.actor.default-dispatcher-65 
User mfa access enabled but is not authenticated

2014-11-05 14:05:39,635 - [DEBUG] - from application in play-akka.actor.default-dispatcher-65 
Clearing invalid session credentials

2014-11-05 14:07:40,295 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:07:40,329 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:07:40,340 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:08:29,980 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:08:30,012 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:08:30,022 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-05 14:08:30,038 - [DEBUG] - from application in play-akka.actor.default-dispatcher-85 
User mfa access enabled but is not authenticated

2014-11-05 14:08:30,039 - [DEBUG] - from application in play-akka.actor.default-dispatcher-85 
Clearing invalid session credentials

2014-11-05 14:08:41,574 - [DEBUG] - from application in play-akka.actor.default-dispatcher-89 
Check result status: approved

2014-11-05 14:08:41,602 - [DEBUG] - from application in play-akka.actor.default-dispatcher-89 
User mfa access enabled but is not authenticated

2014-11-05 14:08:41,602 - [DEBUG] - from application in play-akka.actor.default-dispatcher-89 
Clearing invalid session credentials

2014-11-05 14:09:34,704 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:postgresql://localhost/acceptto-mfa-java

2014-11-05 14:09:34,739 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-3 
Existing EbeanServer [default] is being replaced?

2014-11-05 14:09:34,758 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-11-05 14:09:42,245 - [DEBUG] - from application in play-akka.actor.default-dispatcher-92 
Check result status: approved

2014-11-05 14:09:56,892 - [DEBUG] - from application in play-akka.actor.default-dispatcher-96 
Check result status: rejected

2014-11-05 14:09:56,918 - [DEBUG] - from application in play-akka.actor.default-dispatcher-96 
User mfa access enabled but is not authenticated

2014-11-05 14:09:56,918 - [DEBUG] - from application in play-akka.actor.default-dispatcher-96 
Clearing invalid session credentials

2014-11-05 14:10:07,126 - [DEBUG] - from application in play-akka.actor.default-dispatcher-100 
Check result status: approved

